# +----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+-----+------------------------+-----------------------------+
# | Field                      | Type                                                                                                                                                                                                                                                                                                                                                                                                                   | Null | Key | Default                | Extra                       |
# +----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+-----+------------------------+-----------------------------+
# | TARGET_SERVICE_ID          | bigint(20) unsigned                                                                                                                                                                                                                                                                                                                                                                                                    | NO   | PRI | NULL                   | auto_increment              |
# | TARGET_ID                  | bigint(20) unsigned                                                                                                                                                                                                                                                                                                                                                                                                    | NO   | MUL | NULL                   |                             |
# | SERVICE_TYPE               | enum('getSelectedFullTxt','getFullTxt','getDOI','getMessageNoFullTxt','getHolding','getDocumentDelivery','getBookReview','getTOC','getAbstract','getAlikeRecord','getAuthor','getCitedAuthor','getCitedReference','getCitedJournal','getReference','getCitedBook','getCitedGenome','getCitedRecord','getAuthorEmail','getSubject','getWebService','getWebSearch','getPayPerView','getRecommendation','getMsgNoRecomm') | NO   |     | getFullTxt             |                             |
# | SERVICE_PUBLIC_DESCRIPTION | tinytext                                                                                                                                                                                                                                                                                                                                                                                                               | YES  |     | NULL                   |                             |
# | DESCRIPTION                | tinytext                                                                                                                                                                                                                                                                                                                                                                                                               | YES  |     | NULL                   |                             |
# | KB_INTERNAL_DESCRIPTION    | mediumtext                                                                                                                                                                                                                                                                                                                                                                                                             | YES  |     | NULL                   |                             |
# | TARGET_PARSER_PROGRAM      | varchar(50)                                                                                                                                                                                                                                                                                                                                                                                                            | YES  |     |                        |                             |
# | PARSE_PARAM                | text                                                                                                                                                                                                                                                                                                                                                                                                                   | YES  |     | NULL                   |                             |
# | TARGET_DISPLAYER_PROGRAM   | varchar(50)                                                                                                                                                                                                                                                                                                                                                                                                            | YES  |     |                        |                             |
# | OBJECT_LOOKUP              | enum('Y','N')                                                                                                                                                                                                                                                                                                                                                                                                          | NO   | MUL | Y                      |                             |
# | LINKING_LEVEL              | enum('ARTICLE','ARTICLE_DOI','CITATION','BOOK','ISSUE','VOLUME','JOURNAL','DATABASE')                                                                                                                                                                                                                                                                                                                                  | NO   |     | JOURNAL                |                             |
# | IS_FREE                    | int(1)                                                                                                                                                                                                                                                                                                                                                                                                                 | NO   |     | 0                      |                             |
# | CROSSREF_SUPPORTED         | int(1)                                                                                                                                                                                                                                                                                                                                                                                                                 | NO   |     | 0                      |                             |
# | THRESHOLD                  | text                                                                                                                                                                                                                                                                                                                                                                                                                   | YES  |     | NULL                   |                             |
# | AUTOLOADER_USED            | enum('1','0')                                                                                                                                                                                                                                                                                                                                                                                                          | YES  |     | 0                      |                             |
# | OWNER                      | varchar(100)                                                                                                                                                                                                                                                                                                                                                                                                           | NO   |     |                        |                             |
# | AVAILABLE_FOR              | varchar(100)                                                                                                                                                                                                                                                                                                                                                                                                           | NO   |     |                        |                             |
# | LOGIC_UPDATE_DATE          | timestamp                                                                                                                                                                                                                                                                                                                                                                                                              | NO   |     | 0000-00-00 00:00:00    |                             |
# | STATUS                     | enum('ACTIVE','WITHDRAWN')                                                                                                                                                                                                                                                                                                                                                                                             | YES  |     | ACTIVE                 |                             |
# | STATUS_DATE                | timestamp                                                                                                                                                                                                                                                                                                                                                                                                              | NO   |     | 0000-00-00 00:00:00    |                             |
# | DISTRIBUTION_STATUS        | enum('READY FOR DISTRIBUTION','NOT FOR DISTRIBUTION')                                                                                                                                                                                                                                                                                                                                                                  | YES  |     | READY FOR DISTRIBUTION |                             |
# | DISTRIBUTION_STATUS_DATE   | timestamp                                                                                                                                                                                                                                                                                                                                                                                                              | NO   |     | 0000-00-00 00:00:00    |                             |
# | CREATION_DATE              | timestamp                                                                                                                                                                                                                                                                                                                                                                                                              | NO   |     | 0000-00-00 00:00:00    |                             |
# | CREATED_BY                 | varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                           | NO   |     |                        |                             |
# | LAST_UPDATE_DATE           | timestamp                                                                                                                                                                                                                                                                                                                                                                                                              | NO   |     | CURRENT_TIMESTAMP      | on update CURRENT_TIMESTAMP |
# | LAST_UPDATED_BY            | varchar(255)                                                                                                                                                                                                                                                                                                                                                                                                           | NO   |     |                        |                             |
# | VERSION_NUMBER             | int(10)                                                                                                                                                                                                                                                                                                                                                                                                                | NO   |     | 1                      |                             |
# | RELEASE_NUMBER             | int(10)                                                                                                                                                                                                                                                                                                                                                                                                                | NO   |     | 1                      |                             |
# | CRUD_TYPE                  | enum('CREATE','UPDATE','DELETE')                                                                                                                                                                                                                                                                                                                                                                                       | NO   |     | CREATE                 |                             |
# +----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+-----+------------------------+-----------------------------+
module Sfx4
  module Global
    class KbTargetSerivce < ActiveRecord::Base
      self.table_name = 'KB_TARGET_SERIVCES'
      self.primary_key = 'TARGET_SERVICE_ID'
      self.establish_connection :sfx_global
    end
  end
end
