version: '3.7'
x-build: &build
  build:
    context: .
    cache_from:
      - getit
      - nyulibraries/getit
      - nyulibraries/getit:$BRANCH_NO_SLASH
  image: getit
x-test-env: &test-env
  <<: *build
  environment:
    RAILS_ENV: test
    GETIT_DB_DATABASE: getit_test
    BRANCH_NO_SLASH:
  env_file:
    - test.env
x-dev-env: &dev-env
  <<: *build
  env_file:
    - test.env

services:
  dev:
    <<: *dev-env
    tty: true
    stdin_open: true
    volumes:
      - ./app:/app/app
      - ./vendor:/app/vendor
    ports:
      - "3000:3000"
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - setup_dev

  setup_dev:
    <<: *dev-env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rake", "db:setup"]
    depends_on:
      - db

  test:
    <<: *test-env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rake"]
    depends_on:
      - setup_test

  setup_test:
    <<: *test-env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
