version: '3'
services:

  dev:
    build: .
    volumes:
      - .:/app
      # - ./vendor:/app/vendor
    ports:
      - "3000:3000"
    env_file:
      - test.env
      # - dev.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "tail", "-f", "/dev/null"]
    depends_on:
      - setup_dbs

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      RAILS_ENV: test
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake"]
    depends_on:
      - setup_test_dbs

  setup_test_dbs:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      RAILS_ENV: test
      GETIT_DB_HOST: db
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  setup_dbs:
    build: .
    environment:
      GETIT_DB_HOST: db
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
