version: '3.7'
x-build-image: &build-image
  build:
    context: .
    cache_from:
      - getit
      - quay.io/nyulibraries/getit
      - quay.io/nyulibraries/getit:$BRANCH_NO_SLASH
  environment:
    BRANCH_NO_SLASH:

services:
  getit_1:
    <<: *build-image
    image: getit
  getit_2:
    <<: *build-image
    image: "quay.io/nyulibraries/getit:latest"
    depends_on:
      - getit_1
  getit_3:
    <<: *build-image
    image: "quay.io/nyulibraries/getit:${BRANCH_NO_SLASH}"
    depends_on:
      - getit_2
  getit_4:
    <<: *build-image
    image: "quay.io/nyulibraries/getit:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}"
    depends_on:
      - getit_3
