version: '3.7'
x-build: &build
  build:
    context: .
    cache_from:
      - getit
      - quay.io/nyulibraries/getit
      - quay.io/nyulibraries/getit:$BRANCH_NO_SLASH
  image: getit
x-test-env: &test-env
  <<: *build
  environment:
    RAILS_ENV: test
    GETIT_DB_DATABASE: getit_test
    BRANCH_NO_SLASH:
    CI:
    COVERALLS_REPO_TOKEN:
    TERM: xterm
    PAGER: more
    GOOGLE_ANALYTICS_TRACKING_CODE: '12345'
  env_file:
    - test.env
x-dev-env: &dev-env
  <<: *build
  env_file:
    - test.env

services:
  dev:
    <<: *dev-env
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - setup_dev
    # volumes:
    #   - .:/app

  setup_dev:
    <<: *dev-env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rake", "db:setup"]
    depends_on:
      - db

  test:
    <<: *test-env
    tty: true
    stdin_open: true
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rake"]
    depends_on:
      - setup_test
    # volumes:
    #   - .:/app

  setup_test:
    <<: *test-env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "bundle", "exec", "rake", "db:setup"]
    depends_on:
      - db

  db:
    image: library/mysql:5.6
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  deploy:
    <<: *test-env
    tty: true
    stdin_open: true
    command: "mkdir -p ~/.ssh && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts && \
              bundle exec cap staging deploy:setup && bundle exec cap staging deploy"
    user: root
    environment:
      GIT_BRANCH: "$GIT_BRANCH"
      SSH_AUTH_SOCK: '/ssh-agent'
    volumes:
      - "${HOST_SSH_AUTH_SOCK}:/ssh-agent"
