version: '3'
services:

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - test.env
    command: "tail -f /dev/null"
    depends_on:
      - setup_dbs

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  test:
    build: .
    volumes:
      - .:/app
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: "tail -f /dev/null"
    depends_on:
      - setup_dbs

  setup_dbs:
    build: .
    volumes:
      - .:/app
    environment:
      GETIT_DB_HOST: db
    command: bash -c "sleep 5; rake db:setup"
    depends_on:
      - db
