docker-defaults: &docker-defaults
  docker:
    - image: nyulibraries/circleci_docker:18.06.1-ce-git-compose-1.22.0
      environment:
        - IMAGE_NAME=getit
        - COMPOSE_PROJECT_NAME=getit
  working_directory: ~/app

auth_ecr: &auth_ecr
  run:
    name: Authenticate ECR
    command: |
      eval $(aws ecr get-login --no-include-email --region us-east-1)

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker-compose build dev
      docker-compose -f docker-compose.build.yml build

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker pull ${ECR_DOMAIN}/${IMAGE_NAME}:${BRANCH_NO_SLASH} || docker pull ${ECR_DOMAIN}/${IMAGE_NAME}:latest

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker push ${ECR_DOMAIN}/${IMAGE_NAME}:latest
      docker push ${ECR_DOMAIN}/${IMAGE_NAME}:${BRANCH_NO_SLASH}
      docker push ${ECR_DOMAIN}/${IMAGE_NAME}:${BRANCH_NO_SLASH}-${CIRCLE_SHA1}

run_tests: &run_tests
  run:
    name: Run tests
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker-compose run test

junit_reports: &junit_reports
  - run:
      name: Get Junit tests from stopped container
      when: always
      command: docker cp getit_test_run_1:/app/test-results .
  - store_test_results:
      path: ~/app/test-results
  - store_artifacts:
      path: ~/app/test-results

version: 2
jobs:
  test:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *auth_ecr
      - <<: *pull_docker
      - <<: *build_docker
      - <<: *push_docker
      - <<: *run_tests
      - <: *junit_reports

  deploy-dev:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - run:
          name: Deploy into staging via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/GetIt/job/GetIt%20Development%20Deploy/build/api

  deploy-qa:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - run:
          name: Deploy into QA via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/GetIt/job/GetIt%20QA%20Deploy/build/api

  deploy-prod:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - run:
          name: Deploy into production via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/GetIt/job/GetIt%20Production%20Deploy/build/api

  deploy-reindex:
    <<: *docker-defaults
    steps:
      - setup_remote_docker
      - run:
          name: Deploy into reindex environment via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/GetIt/job/GetIt%20Reindex%20Deploy/build/api

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - deploy-dev:
          requires:
              - test
          filters:
            branches:
              ignore:
                - master
                - qa
      - deploy-qa:
          requires:
              - test
          filters:
            branches:
              only: qa
      - deploy-prod:
          requires:
              - test
          filters:
            branches:
              only: master
