# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
# UMLAUT: mysql db with mysql2 adapter strongly recommended for Umlaut, in both
# production and development. sqlite3 has unclear semantics under threaded
# concurrency which umlaut uses, and in many cases simply does not work.
#
# A high (connection) pool setting is also, sadly, generally
# required at present.
#
# development:
#   adapter: mysql2
#   host:
#   username:
#   password:
#   database:
#   pool: 30
#
mysql: &mysql
  adapter: mysql2
  encoding: utf8

getit: &getit
  <<: *mysql
  reconnect: false
  pool: 12
  checkout_timeout: 2
  host: <%= (ENV['GETIT_DB_HOST'] || 'localhost') %>
  username: <%= (ENV['GETIT_DB_USER'] || 'root') %>
  password: <%= (ENV['GETIT_DB_PASSWORD'] || '') %>
  database: <%= (ENV['GETIT_DB_DATABASE'] || 'getit') %>

development: &development
  <<: *getit

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  <<: *getit
  database: <%= (ENV['GETIT_DB_DATABASE'] || 'getit_test') %>

cucumber:
  <<: *test

staging:
  <<: *getit

qa:
  <<: *getit

production:
  <<: *getit

sfx: &sfx
  <<: *mysql
  port: ENV['SFX_DB_PORT']
  pool: 5

<% if ENV['NYU_SFX_DB_HOST'] %>
sfx_db:
  <<: *sfx
  host: <%= ENV['NYU_SFX_DB_HOST'] %>
  username: <%= ENV['NYU_SFX_DB_USER'] %>
  password: <%= ENV['NYU_SFX_DB_PASSWORD'] %>
  database: <%= ENV['NYU_SFX_DB_DATABASE'] %>
<% end %>

<% if ENV['CU_SFX_DB_HOST'] %>
sfx4_cu:
  <<: *sfx
  host: <%= ENV['CU_SFX_DB_HOST'] %>
  username: <%= ENV['CU_SFX_DB_USER'] %>
  password: <%= ENV['CU_SFX_DB_PASSWORD'] %>
  database: <%= ENV['CU_SFX_DB_DATABASE'] %>
<% end %>

<% if ENV['NS_SFX_DB_HOST'] %>
sfx4_ns:
  <<: *sfx
  host: <%= ENV['NS_SFX_DB_HOST'] %>
  username: <%= ENV['NS_SFX_DB_USER'] %>
  password: <%= ENV['NS_SFX_DB_PASSWORD'] %>
  database: <%= ENV['NS_SFX_DB_DATABASE'] %>
<% end %>

<% if ENV['GLOBAL_SFX_DB_HOST'] %>
sfx4_global:
  <<: *sfx
  host: <%= ENV['GLOBAL_SFX_DB_HOST'] %>
  username: <%= ENV['GLOBAL_SFX_DB_USER'] %>
  password: <%= ENV['GLOBAL_SFX_DB_PASSWORD'] %>
  database: <%= ENV['GLOBAL_SFX_DB_DATABASE'] %>
<% end %>
