# Configuration file for BobCat institutions.
NYU:
  getit_url: https://qa.getit.library.nyu.edu/nyu/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  views:
    breadcrumbs:
      title: NYU Libraries
      url: http://dev.library.nyu.edu
    ill:
      url: http://dev.ill.library.nyu.edu
    tabs:
      all:
        url: http://bobcatdev.library.nyu.edu
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYU&tab=reserves'

NYUSH:
  getit_url: https://qa.getit.library.nyu.edu/nyush/resolve?
  views:
    ill:
      url: http://dev.ill.library.nyu.edu
    tabs:
      all:
        url: http://bobcatdev.library.nyu.edu/nyush
      remote:
        url: https://qa.arch.library.nyu.edu/nyush
      databases:
        url: https://qa.arch.library.nyu.edu/nyush/databases/alphabetical/
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYUSH&tab=nyushcr'

NYUAD:
  getit_url: https://qa.getit.library.nyu.edu/nyuad/resolve?
  views:
    ill:
      url: http://dev.ill.library.nyu.edu
    tabs:
      all:
        url: http://bobcatdev.library.nyu.edu/nyuad
      remote:
        url: https://qa.arch.library.nyu.edu/nyuad
      databases:
        url: https://qa.arch.library.nyu.edu/nyuad/databases/alphabetical/
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYUAD&tab=nyuadcr'

CU:
  getit_url: https://qa.getit.library.nyu.edu/cu/resolve?
  views:
    tabs:
      all:
        url: http://bobcatdev.library.nyu.edu/cooper
      cu:
        url: "http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=CU&tab=cu"
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=CU&tab=cucr'


NS:
  getit_url: https://qa.getit.library.nyu.edu/ns/resolve?
  views:
    ill:
      url: http://dev.ill.library.nyu.edu
    tabs:
      all:
        url: http://bobcatdev.library.nyu.edu/newschool
      ns:
        url: "http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NS&tab=ns"
      remote:
        url: https://qa.arch.library.nyu.edu/ns
      databases:
        url: https://qa.arch.library.nyu.edu/ns/databases/alphabetical/
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NS&tab=nscr'

HSL:
  getit_url: https://qa.getit.library.nyu.edu/hsl/resolve?
  views:
    tabs:
      all:
        url: "http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=HSL&tab=all"

NYSID:
  views:
    ill:
      url: http://dev.ill.library.nyu.edu
    tabs:
      nysid:
        url: http://bobcatdev.library.nyu.edu/nysid
      all:
        url: http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYSID&tab=all
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYSID&tab=reserves'
