# Default Settings
databases:
  host: localhost
  database: nyu_getit_test
  username: root
  password:

#
# UMLAUT: for the 'search' functions (A-Z title lookup) to work, you need
# a direct database connection to the SFX database, under 'sfx_db' key.
# You should manually set up a new read-only MySQL account in the SFX db
# for this purpose, rather than use one of the full-access existing SFX
# mysql accounts.
#
#sfx_db:
#  adapter: mysql2
#  host: my_sfx_host.u.edu
#  port: 3310 # 3310 is defualt SFX embedded mysql port
#  database: sfxlcl41 # or other sfx instance db
#  username:
#  password:
#  pool: 5
#  encoding: utf8
#
# UMLAUT: for Sfx4Solr functionality.  If you're not using SFX 4 indexed in
# Solr via Sunspot, feel free to ignore this.
#sfx4_global:
#  adapter: mysql2
#  host: my_sfx_host.u.edu
#  port: 3310 # 3310 is defualt SFX embedded mysql port
#  database: sfxglb41 # or other sfx global db
#  username:
#  password:
#  pool: 5
#  encoding: utf8
#
sfx_databases: {}

institutions:
  default:
    views:
      sfx_base_url: "http://sfx.library.nyu.edu/sfxlcl41?"
    services:
      NYU_Primo:
        base_url: "http://primo.library.edu"
      Amazon:
        api_key: api_key
        secret_key: secret_key
        associate_tag: associate_tag
      NYU_Primo_Source:
        base_url: "http://primo.library.nyu.edu"
      CoverThing:
        developer_key: developer_key
      GoogleBookSearch:
        api_key: api_key
      IsbnDb:
        access_key: access_key
  NYU:
    ip_addresses:
      - 127.0.0.1
    services:
      NYU_SFX:
        base_url: "http://sfx.library.nyu.edu/sfxlcl41"
      ScopusCitations:
        json_api_key: json_api_key
      NYUUlrichsLink:
        base_url: ""
      NYU_RefWorks:
        base_url: ""
      NYU_Endnote:
        base_url: ""
      NYU_EASYBIB:
        base_url: ""
      NYU_RIS:
        base_url: ""
      NYU_BIBTEX:
        base_url: ""
      NYU_ILLiad:
        base_url: ""
  NYUAD:
    ip_addresses: []
  NYSID:
    ip_addresses: []
  HSL:
    ip_addresses: []
  CU:
    ip_addresses: []
  NS:
    ip_addresses: []
    services:
      NS_bX:
        token: token

capistrano:
  servers: []
  user: 
  path: 
  scm_username: 

sunspot:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /

newrelic:
  api_key: 
  app_name: GetIt

secret_token: 463206801748738fefdf3eaa59b757595470827db80ec5e34c80aa3ec1e8865f52756275f5fa95911ed9e7e184eea4dedaca91423c7f0442f5fe4f0568607ed2