production:
  solr:
    hostname: <%= Settings.sunspot.solr.hostname %>
    path: <%= Settings.sunspot.solr.path %>
    port: <%= Settings.sunspot.solr.port %>
    log_level: <%= Settings.sunspot.solr.log_level %>

qa:
  solr:
    hostname: <%= Settings.sunspot.solr.hostname %>
    path: <%= Settings.sunspot.solr.path %>
    port: <%= Settings.sunspot.solr.port %>
    log_level: <%= Settings.sunspot.solr.log_level %>

staging:
  solr:
    hostname: <%= Settings.sunspot.solr.hostname %>
    path: <%= Settings.sunspot.solr.path %>
    port: <%= Settings.sunspot.solr.port %>
    log_level: <%= Settings.sunspot.solr.log_level %>

test:
  solr:
    hostname: <%= Settings.sunspot.solr.hostname %>
    path: <%= Settings.sunspot.solr.path %>
    port: <%= Settings.sunspot.solr.port %>
    log_level: <%= Settings.sunspot.solr.log_level %>

development:
  solr:
    hostname: <%= Settings.sunspot.solr.hostname %>
    path: <%= Settings.sunspot.solr.path %>
    port: <%= Settings.sunspot.solr.port %>
    log_level: <%= Settings.sunspot.solr.log_level %>
