production:
  solr:
    hostname: index.websolr.com
    path: /solr/f0fdfe03534
    port: 80
    log_level: WARNING

development:
  solr:
    hostname: index.websolr.com
    path: /solr/f0fdfe03534
    port: 80
    log_level: WARNING

test:
  solr:
    hostname: index.websolr.com
    path: /solr/f0fdfe03534
    port: 80
    log_level: WARNING
